import re

import librosa
import numpy as np


class AudioFeatures:
    """
    Extract useful speaking metrics from an audio file.
    """

    def analyze(self, audio_path, transcript):
        """
        Parameters
        ----------
        audio_path : str
            Temporary audio file path.

        transcript : str
            Text generated by Whisper.

        Returns
        -------
        dict
            Dictionary containing audio metrics.
        """

        try:

            # Load audio
            audio, sample_rate = librosa.load(
                audio_path,
                sr=None
            )

            # ---------------------------------
            # Duration
            # ---------------------------------
            duration = librosa.get_duration(
                y=audio,
                sr=sample_rate
            )

            # ---------------------------------
            # Voice Energy
            # ---------------------------------
            rms = librosa.feature.rms(
                y=audio
            )[0]

            average_energy = float(
                np.mean(rms)
            )

            # ---------------------------------
            # Word Count
            # ---------------------------------
            words = transcript.split()

            total_words = len(words)

            # ---------------------------------
            # Words Per Minute
            # ---------------------------------
            if duration > 0:

                wpm = round(
                    (total_words / duration) * 60
                )

            else:

                wpm = 0

            # ---------------------------------
            # Filler Words
            # ---------------------------------
            fillers = [
                "um",
                "uh",
                "like",
                "actually",
                "basically",
                "you know",
                "so"
            ]

            transcript_lower = transcript.lower()

            filler_count = 0

            for filler in fillers:

                filler_count += len(
                    re.findall(
                        r"\b" + re.escape(filler) + r"\b",
                        transcript_lower
                    )
                )

            # ---------------------------------
            # Pause Ratio
            # ---------------------------------

            estimated_speaking_time = total_words * 0.45

            if duration > 0:

                pause_ratio = max(
                    0,
                    (
                        duration -
                        estimated_speaking_time
                    ) / duration
                )

            else:

                pause_ratio = 0

            pause_ratio = round(
                pause_ratio * 100,
                2
            )

            # ---------------------------------
            # Return Metrics
            # ---------------------------------

            return {

                "duration": round(duration, 2),

                "word_count": total_words,

                "wpm": wpm,

                "energy": round(
                    average_energy,
                    4
                ),

                "pause_ratio": pause_ratio,

                "filler_count": filler_count

            }

        except Exception as e:

            raise Exception(
                f"Audio Analysis Error: {str(e)}"
            )